version: '3.8'
services:
  vprodb:
    build: 
       context: ./Dockerfiles/db
    image: kubelaxmi/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache:
    image: memecached 
    ports:
      - "11211:11211"

  vpromq:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: 
       context: ./Dockerfiles/app
    image: kubelaxmi/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: 
       context: ./Dockerfiles/web
    image: kubelaxmi/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes: 
  vprodbdata: {}
  vproappdata: {}